//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminAlmacen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_detail
    {
        public int id { get; set; }
        public int id_invoice { get; set; }
        public int id_product { get; set; }
        public int cost { get; set; }
        public int quantity { get; set; }
    
        public virtual invoice invoice { get; set; }
        public virtual products products { get; set; }
    }
}
