//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminAlmacen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public provider()
        {
            this.products = new HashSet<products>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public int id_user { get; set; }
        public Nullable<int> id_contact { get; set; }
        public Nullable<int> id_location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<products> products { get; set; }
        public virtual user user { get; set; }
    }
}
