//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminAlmacen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_operation
    {
        public int id { get; set; }
        public int id_role { get; set; }
        public int id_operation { get; set; }
    
        public virtual operation operation { get; set; }
        public virtual role role { get; set; }
    }
}
